# Generated by Django 6.0.5 on 2026-05-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='temp_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='password',
            field=models.CharField(default='temp_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='temp_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='password',
            field=models.CharField(default='temp_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='password',
            field=models.CharField(default='temp_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receptionist',
            name='password',
            field=models.CharField(default='temp_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(default='temp_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='temp_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='password',
            field=models.CharField(default='temp_password', max_length=128),
            preserve_default=False,
        ),
    ]
