# Generated by Django 6.0.5 on 2026-05-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_theme_remove_admin_system_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='primary',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
