# Generated by Django 6.0.5 on 2026-05-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_theme_primary_alter_theme_secondary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
